class ElementMenu {
  final String title, image, typeWeight, currency, infoProduct, description;
  final double price, weight, id, time, calories;

  ElementMenu({
    required this.id,
    required this.title,
    required this.image,
    required this.price,
    required this.weight,
    required this.typeWeight,
    required this.currency,
    required this.infoProduct,
    required this.time,
    required this.calories,
    required this.description,
  });
}

class CategoryMenu {
  final String category;
  final List<ElementMenu> items;

  CategoryMenu({required this.category, required this.items});
}

final List<CategoryMenu> demoCategoryMenus = [
  CategoryMenu(
    category: "Salads",
    items: [
      ElementMenu(
          id: 1,
          currency: "USD",
          price: 4,
          image: "cesar.jpg",
          title: "Cheese",
          infoProduct: "croutons, romaine, anchovies, parmeasan cheese, olive oil, vinegar and plenty of black pepper.",
          weight: 222,
          typeWeight: "g",
          time: 3,
          calories: 500,
          description: "The salad\u0027s creation is generally attributed to the restaurateur Caesar Cardini, an Italian immigrant who operated restaurants in Mexico and the United States. His daughter Rosa recounted that her father invented the salad at his Prohibition-era restaurant in Tijuana, Mexico when a Fourth of July rush in 1924 depleted the kitchen\u0027s supplies. (Cardini lived in San Diego but ran the family restaurant in Tijuana to attract American customers seeking to circumvent the restrictions of the Prohibition). Cardini made do with what he had, adding the dramatic flair of the table-side tossing \"by the chef.\" A number of Cardini\u0027s staff have said that they invented the dish.",
      ),
      ElementMenu(
          id: 2,
          currency: "USD",
          price: 5,
          image: "grek.jpg",
          title: "Greek salad",
          infoProduct: "Lettuce, tomatoes, feta, olives, cucumber",
          weight: 220,
          typeWeight: "g",
          time: 3,
          calories: 300,
          description: "Various other salads have also been called \"Greek\" in the English language in the last century, including some with no apparent connection to Greek cuisine. A 1925 Australian newspaper described a Greek salad of boiled squash dressed with sour milk; a 1934 American newspaper described a mayonnaise-dressed lettuce salad with shredded cabbage and carrots",      ),
      ElementMenu(
          id: 3,
          currency: "USD",
          price: 8,
          image: "semga.jpg",
          title: "Salmon salad",
          infoProduct: "Potato chips with salt",
          weight: 250,
          typeWeight: "g",
          time: 3,
          calories: 400,
          description: "Various other salads have also been called \"Greek\" in the English language in the last century, including some with no apparent connection to Greek cuisine. A 1925 Australian newspaper described a Greek salad of boiled squash dressed with sour milk; a 1934 American newspaper described a mayonnaise-dressed lettuce salad with shredded cabbage and carrots",
      ),
      ElementMenu(
          id: 4,
          currency: "USD",
          price: 7,
          image: "hunting.jpg",
          title: "Hunting salad",
          infoProduct: "sausages, potatoes, greens",
          weight: 220,
          typeWeight: "g",
          time: 4,
          calories: 390,
          description: "Hunting salad has such a name, since it includes meat of animals caught by hunters. History is silent at what point the game meat was replaced with beef, hunting sausages or even pork, but in our reality it is these meat products that are used for such a salad. The salad turns out to be very satisfying, nutritious and quite dense � ideal for men\u0027s snacks.",
      )
    ],
  ),
  CategoryMenu(
      category: "Soups",
      items: [
        ElementMenu(
          id: 5,
          currency: "USD",
          price: 10,
          image: "solyanka.jpg",
          title: " Solyanka soup",
          infoProduct: "sausage, potato, onion, tomato, pickle",
          weight: 300,
          typeWeight: "g",
          time: 15,
          calories: 300,
          description: "There is no consensus on the correctness of the name selyanka in relation to soup. Russian linguist and writer L. I. Skvortsov writes about the traditionality of the name selyanka and the ambiguity of the etymology of the word \"solyanka\", at the same time, Russian historian, researcher and popularizer of cooking V. V. Pokhlebkin writes about the incorrectness and distortion of the name selyanka and claims that the name solyanka is fixed in the \"House-building\" of 1547, while the term selyanka took root only in the XIX century and at the beginning of the XX century was again replaced by the term solyanka. The Dictionary of the Russian Academy (1794) indicated the name solyanka as the main variant, and marked the selyanka variant as \"simple\"",
        ),
        ElementMenu(
          id: 6,
          currency: "USD",
          price: 8,
          image: "borsch.jpg",
          title: "Borsch soup",
          infoProduct: "meat, carrots, onions, potatoes, beets, white cabbage, beans, tomato paste, vegetable oil, bay leaf, sugar, vinegar",
          weight: 300,
          typeWeight: "g",
          time: 15,
          calories: 300,
          description: "In the old days, borscht was called soup made from borscht. Later borscht was cooked on beet kvass: it was diluted with water, the mixture was poured into a clay pot or cast iron and brought to a boil. Chopped beets, cabbage, carrots and other vegetables were put in boiling water and put the pot in the oven. The cooked borscht was salted and refilled",
        ),
        ElementMenu(
          id: 7,
          currency: "USD",
          price: 10,
          image: "mushroom.jpg",
          title: "Mushroom soup",
          infoProduct: "potatoes, onions, herbs, salt, pepper, vegetable oil, mushrooms, soft processed cheese",
          weight: 230,
          typeWeight: "g",
          time: 16,
          calories: 320,
          description: "Cream soup with mushrooms has been prepared since about the 17th century, when entrepreneurs already learned how to grow champignons in artificial conditions. It was in France, so this country is considered the birthplace of mushroom soups-puree. But the soup with dried porcini mushrooms is cooked on water and already only one aroma, spreading around the house, can drive even the most refined gourmets crazy.",
        )
      ],
  ),
  CategoryMenu(
      category: "Snacks",
      items: [
        ElementMenu(
          id: 8,
          currency: "USD",
          price: 4,
          image: "crackers.png",
          title: "Crackers",
          infoProduct: "bread, garlic, salt, oil",
          weight: 200,
          typeWeight: "g",
          time: 12,
          calories: 600,
          description: "Crackers are second-baked bread, \"dried for the purpose of either storage or further culinary use in various dishes,\" is the definition of the product given by William Pohlebkin (1923-2000), a Russian historian and writer. The main distinguishing feature of crackers from all other bakery products is their reduced humidity, ideally no more than forty-nine percent, more often - up to eight.",
        ),
        ElementMenu(
          id: 9,
          currency: "USD",
          price: 4,
          image: "croutons.jpg",
          title: "Croutons",
          infoProduct: "white bread, garlic, salt, pepper, oil",
          weight: 200,
          typeWeight: "g",
          time: 12,
          calories: 580,
          description: "Croutons are made from any bread and are used as a light snack, for example, croutons with garlic for beer, or as an ingredient in soups, broths, salads (\"Caesar\"), cutlets and other dishes. To add to soups (French onion soup), bread is simply fried with salt and/or black pepper.",
        ),
        ElementMenu(
          id: 11,
          currency: "USD",
          price: 7,
          image: "chips.jpg",
          title: "Chips",
          infoProduct: "potatoes, salt, pepper, oil",
          weight: 100,
          typeWeight: "g",
          time: 3,
          calories: 330,
          description: "",
        ),
      ]
  ),
  CategoryMenu(
    category: "Alcohol",
    items: [
      ElementMenu(
          id: 0987651111,
          currency: "USD",
          price: 3,
          image: "ballantine.jpg",
          title: "Ballantine's whiskey",
          infoProduct: "Blended Scotch whiskey Ballantine's 12 Years Old is made from more than 40 selected varieties of grain and malt whiskey, the minimum aging period of which is 12 years.",
          weight: 50,
          typeWeight: "milliliter",
          time: 3,
          calories: 330,
          description: "",
      ),
      ElementMenu(
          id: 0987654344,
          currency: "USD",
          price: 3,
          image: "jameson.jpg",
          title: "Jameson whiskey",
          infoProduct: "Jameson whiskey is the most famous Irish whiskey. The best grains are selected for it. It gets its trademark softness thanks to triple distillation and is aged in oak barrels for at least 4 years.",
          weight: 50,
          typeWeight: "milliliter",
          time: 3,
          calories: 330,
          description: "",
      ),
      ElementMenu(
          id: 0987654344,
          currency: "USD",
          price: 3,
          image: "light.jpg",
          title: "Light beer",
          infoProduct: "Light wheat ale in the Bavarian style. Wheat malt makes it soft and enveloping, while a special strain of yeast adds hints of clove and banana to the aroma.",
          weight: 500,
          typeWeight: "milliliter",
          time: 3,
          calories: 330,
          description: "",
      ),
      ElementMenu(
          id: 0987654344,
          currency: "USD",
          price: 3,
          image: "dark.jpg",
          title: "Dark beer",
          infoProduct: "Porter with a dense malt base, caramel sweetness and hints of chocolate and espresso on the palate.",
          weight: 500,
          typeWeight: "milliliter",
          time: 3,
          calories: 330,
          description: "",
      ),
    ],
  ),
];
